  version: "3.9"

  services:
    postgres:
      image: postgres:16-alpine
      container_name: keycloak_pg_iam
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        POSTGRES_DB: plt_iam_master_db
      ports:
        - "5431:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./init-db:/docker-entrypoint-initdb.d

    keycloak:
      image: quay.io/keycloak/keycloak:26.3.2
      container_name: keycloak_compose
      depends_on:
        - postgres
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/plt_iam_master_db
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
      ports:
        - "8080:8080"
      command: start-dev

  volumes:
    pgdata:
